version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/lambda/type-b/chatbot"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/lambda/type-b/send_email"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/lambda/type-a/tools/reader"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/lambda/type-a/interface"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/lambda/type-a/execution/reservation"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/lambda/type-b/sentinel_executioner"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/lambda/type-b/sentinel_release"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/internal-infra/lambda/rag_query"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/internal-infra/lambda/sentinel_enterprise"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/internal-infra/lambda/sentinel_cloud_native"
    schedule:
      interval: "weekly"
