version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/hotel_folder/lambda/type-b/chatbot"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/hotel_folder/lambda/type-a/tools/reader"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/hotel_folder/lambda/type-a/interface"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/hotel_folder/lambda/type-a/execution/reservation"
    schedule:
      interval: "weekly"
